const DATABASE_NAME = "@gameplay";
const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_NEWAPPOINTMENTS = `${DATABASE_NAME}:myappointments`;

export { COLLECTION_USERS, COLLECTION_NEWAPPOINTMENTS };
